package com.maxrave.simpmusic.ui.theme

import androidx.compose.ui.graphics.Color
import com.maxrave.domain.manager.DataStoreManager
import org.jetbrains.compose.resources.StringResource
import simpmusic.composeapp.generated.resources.Res
import simpmusic.composeapp.generated.resources.theme_palette_amber
import simpmusic.composeapp.generated.resources.theme_palette_berry
import simpmusic.composeapp.generated.resources.theme_palette_forest
import simpmusic.composeapp.generated.resources.theme_palette_lavender
import simpmusic.composeapp.generated.resources.theme_palette_mint
import simpmusic.composeapp.generated.resources.theme_palette_mono
import simpmusic.composeapp.generated.resources.theme_palette_ocean
import simpmusic.composeapp.generated.resources.theme_palette_rose
import simpmusic.composeapp.generated.resources.theme_palette_sky
import simpmusic.composeapp.generated.resources.theme_palette_sunset

/**
 * Theme color source value for the curated named-palette picker.
 *
 * The [DataStoreManager] interface lives in the `core` submodule and only
 * declares [DataStoreManager.THEME_COLOR_DEFAULT] /
 * [DataStoreManager.THEME_COLOR_WALLPAPER] /
 * [DataStoreManager.THEME_COLOR_CUSTOM]. Because
 * [DataStoreManager.setThemeColorSource] takes an arbitrary [String], we
 * add this value on the app side without a submodule change. The selected
 * palette's seed color is persisted through [DataStoreManager.customThemeColor]
 * and resolved in [AppTheme] (which treats a `PALETTE` source identically to
 * `CUSTOM` for seed-color derivation).
 */
const val THEME_COLOR_PALETTE = "PALETTE"

/**
 * A curated named theme palette. [seedHex] is an 8-digit ARGB hex string
 * persisted in [DataStoreManager.customThemeColor]; [AppTheme] feeds it to
 * MaterialKolor to generate the full light/dark ColorScheme.
 */
data class ThemePalette(
    val id: String,
    val nameRes: StringResource,
    val seedHex: String,
) {
    /** MaterialKolor seed for this palette. Falls back to the app default if malformed. */
    val seedColor: Color
        get() = parseThemeColorHex(seedHex) ?: seed
}

/**
 * Curated named theme palettes shown in Settings → Theme color → Palette.
 *
 * Seeds are tuned to read well in both the AMOLED-dark and the neutral-light
 * schemes generated by [AppTheme]. Each entry's [ThemePalette.seedHex] is
 * written to [DataStoreManager.customThemeColor] when the user picks it, so
 * the selection survives restarts and is shared across platforms.
 */
val ThemePalettes: List<ThemePalette> =
    listOf(
        ThemePalette("ocean", Res.string.theme_palette_ocean, "FF0288D1"),
        ThemePalette("sunset", Res.string.theme_palette_sunset, "FFE65100"),
        ThemePalette("forest", Res.string.theme_palette_forest, "FF2E7D32"),
        ThemePalette("lavender", Res.string.theme_palette_lavender, "FF7E57C2"),
        ThemePalette("rose", Res.string.theme_palette_rose, "FFD81B60"),
        ThemePalette("amber", Res.string.theme_palette_amber, "FFFF8F00"),
        ThemePalette("mono", Res.string.theme_palette_mono, "FF607D8B"),
        ThemePalette("mint", Res.string.theme_palette_mint, "FF00897B"),
        ThemePalette("berry", Res.string.theme_palette_berry, "FFAD1457"),
        ThemePalette("sky", Res.string.theme_palette_sky, "FF039BE5"),
    )

/**
 * The palette whose seed matches [seedHex], or null when the stored color
 * is not one of the curated seeds (e.g. a free-form custom color).
 */
fun findThemePalette(seedHex: String?): ThemePalette? =
    seedHex?.let { hex -> ThemePalettes.firstOrNull { it.seedHex.equals(hex, ignoreCase = true) } }
